apiVersion: v2
description: DPS processing
name: ffc-pay-dps
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.7.6
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
